version: "3.7"

services:
    # image project
    app:
        container_name: maisvendas
        build:
            context: .
            dockerfile: Dockerfile
        image: especializati/laravel9-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on: 
            - redis
        networks: 
            - mais-vendas
    
    # nginx
    nginx:
        container_name: maisvendas-nginx
        image: nginx:alpine
        restart: unless-stopped
        ports: 
            - "8000:80"
        volumes: 
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks: 
            - mais-vendas

    # db mysql
    mysql:
        container_name: maisvendas-mysql
        image: mysql:5.7.22
        restart: unless-stopped
        environment: 
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes: 
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports: 
            - "3388:3306"
        networks: 
            - mais-vendas

    # queue
    queue:
        container_name: maisvendas-queue
        image: especializati/laravel9-app
        restart: unless-stopped
        command: "php artisan queue:work"
        volumes: 
            - ./:/var/www
        depends_on: 
            - redis
            - app
        networks: 
            - mais-vendas

    # redis
    redis:
        container_name: maisvendas-redis
        image: redis:latest
        networks: 
            - mais-vendas

networks: 
    mais-vendas:
        driver: bridge
